logging_config:
    filename: "log.txt"
    mode: "w"
    formatter: "%(name)s - %(levelname)s - %(message)s"

flags:
    copy: False
    create_web_files: True
    manifest: False
    process_all_images_for_manifest: True
    file_upload: True
    download_overwrite: True
    image_group_overwrite: True
    test_run: True
    input_from_file: False
    copy_input: True

image_processing:
    resize: True
    rotate: True
    scaling: 2400

test_data: 'Mantras.tsv'

scan_directories:
    web: 'web'
    sources: 'sources'
    images: 'images'

catalog_field_names:
    item_uid: 'itemuid'
    work_uid: 'workuid'
    directory_path: 'directory_path'
    image_group_uid: 'imagegroupuid'

local_image_listing_file: 'data/image_listing.json'
local_source_input_file: 'Mantras.tsv'

google:
    scope:
        - "https://spreadsheets.google.com/feeds"
        - "https://www.googleapis.com/auth/drive"
    credentials:
        iiif: "config/credentials.json"
        nlm: "config/credentials_gs_old.json"
        acip: ".acip_creds.json"
    sheets:
        ids:
            ramachandra_1: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            ramachandra_2: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            iiif: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
        names:
            ramachandra_1: "New"
            ramachandra_2: "New_2"
            ramachandra_3: "New_3"
            scan_input: "aws_input"
            catalog_input: "catalog_input"
            merged_input: "merged_input"
        main_output:
            spreadsheet_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_name: "OUTPUT"
        ramachandra_1_1:
            spreadsheet_id: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            sheet_name: "New"
        ramachandra_1_2:
            spreadsheet_id: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            sheet_name: "New_2"
        ramachandra_1_3:
            spreadsheet_id: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            sheet_name: "New_3"
        previously_gathered:
            spreadsheet_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_name: "full_input"
        test_input:
            spreadsheet_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_name: "INPUT"
        test_output:
            spreadsheet_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_name: "OUTPUT"
        ramachandran:
            spreadsheet_input_id: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            spreadsheet_output_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_input_name: "New"
            sheet_output_name: "output"
        ramachandran_2:
            spreadsheet_input_id: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
            spreadsheet_output_id: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
            sheet_input_name: "New_2"
            sheet_output_name: "output_2"
    sheet_key: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
    sheet_key_test: "1scb2UMLbuuDoGYlnOcFvpW9ZjC54Z6bbiEUeEj-LQQs"
    sheet_mongolia_test: "1SLgnUq4ohrAODB-XNQ6oiVqQxxJmeR0IQPozSpW6xiw"
    sheet_iiif_test: "1NZPbJArxgaAn3x-u5n0zqUxxK2yskd2KoPRmfHx05vE"
    sheet_ramachandran: "1-YPHZj1-YVPs7FW0p5IFKgw4qcGCRklg4WdmDEHuQZs"
    sheet_input: "new"
    sheet_output: "output"
    sheet_names_filter: "new"
    sheet_mongolia_filter: "acip-title-level"

provider:
    digital_ocean:
        source_bucket: 'acip'
        target_bucket: 'acip'
        target_bucket_endpoint: 'scans/unpublished'
        source_bucket_endpoint: 'staging_test/'
        target_s3_url: 'sfo2.digitaloceanspaces.com'
    aws:
        all_bucket: 'all-library'
        main_prefix: 'staging/ramachandra_2'
        source_prefix: 'staging'
        general_prefix: ''
        target_s3_url: 's3-us-west-2.amazonaws.com'

orientation:
    landscape: "top-to-bottom"
    portrait: "left-to-right"
    default: "left-to-right"

MANIFEST_SAVE_DIR: '../manifests'
MIN_IMAGE_SIZE: 32


#
#put_objs = {
#    'Bucket': 'acip',
#    'Body': 'Contents',
#    'Key': ''
#}
#
#operation_parameters = {
#    'Bucket': 'acip',
#    'Delimiter': '/'
#}
